Make the `serve` function public
rustminded/xtask-wasm pull request #59
Opened 2022-08-19 01:24 UTC by yozhgoor

Allows to use the `serve` function directly so we can use `xtask-wasm`'s dev-server without command and watcher.

2022-08-19 02:06 UTC, yozhgoor commented
Implement `Default` on `xtask_watch::Watch` is needed to merge this PR

2022-08-22 13:00 UTC, cecton requested changes

2022-08-22 13:00 UTC, cecton commented on src/dist.rs
> +#[derive(Debug, Default)]
Not sure why you are implementing default here?!

2022-08-23 05:20 UTC, cecton approved these changes

2022-08-23 10:15 UTC, merged